### ISSUE TITLE
Math.IEEEremainder() is doing trouble...

### ISSUE THREAD

**Issue by HilelAmiel** [Programming-TRIGON/RobotCode2020#78]
this function isn't working well with the gyro angle output! for example when reaching an angle of 180 degrees the get angle switch to -180 but when we want to rotate from 170 to -170 pid isnt working with that.

**Comment by EliyaFishman** [comment]
In the simulation, when the setpoint is -170 and the position is 170 the error is 20.
>  pid isnt working with that.

What the PID does and what it should do?
